[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_PDF_EXPORT_ENABLED = "false"
  VITE_ENABLE_DOWNLOADS = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
